runtime: nodejs18
env_variables: 
  DB_HOST: localhost
  DB_USER: root
  DB_PASSWORD:
  DB_DATABASE: pcospal
  DB_DIALECT: mysql
  DB_SOCKET: 

  JWT_SECRET_KEY: MuchSecretVerySecureSoSafe
  OPENAI_API_KEY: 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