runtime: nodejs18
env_variables: 
  DB_HOST: localhost
  DB_USER: root
  DB_PASSWORD:
  DB_DATABASE: pcospal
  DB_DIALECT: mysql
  DB_SOCKET:

  APP_ENV: development 
  
  JWT_SECRET_KEY: MuchSecretVerySecureSoSafe
  OPENAI_API_KEY: 
beta_settings:
  cloud_sql_instances: