steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: 
    - '-c'
    - |
      sed -i "s/<db-host-value>/$$DB_HOST/" app.yaml
      sed -i "s/<db-user-value>/$$DB_USER/" app.yaml
      sed -i "s/<db-password-value>/$$DB_PASSWORD/" app.yaml
      sed -i "s/<db-database-value>/$$DB_DATABASE/" app.yaml
      sed -i "s/<db-dialect-value>/$$DB_DIALECT/" app.yaml
      sed -i "s/<db-socket-value>/$$DB_SOCKET/" app.yaml
      sed -i "s/<app-env-value>/$A$PP_ENV/" app.yaml
      sed -i "s/<jwt-secret-key-value>/$$JWT_SECRET_KEY/" app.yaml
      sed -i "s/<openai-api-key-value>/$$OPENAI_API_KEY/" app.yaml
      sed -i "s/<cloud-sql-instances-value>/$$cloud_sql_instances/" app.yaml
  substitutions:
    _DB_HOST: $DB_HOST
    _DB_USER: $DB_USER
    _DB_PASSWORD: $DB_PASSWORD
    _DB_DATABASE: $DB_DATABASE
    _DB_DIALECT: $DB_DIALECT
    _DB_SOCKET: $DB_SOCKET
    _APP_ENV: $APP_ENV
    _JWT_SECRET_KEY: $JWT_SECRET_KEY
    _OPENAI_API_KEY: $OPENAI_API_KEY
    _CLOUD_SQL_INSTANCES: $cloud_sql_instances
  secretEnv:
    - DB_HOST
    - DB_USER
    - DB_PASSWORD
    - DB_DATABASE
    - DB_DIALECT
    - DB_SOCKET
    - APP_ENV
    - JWT_SECRET_KEY
    - OPENAI_API_KEY
    - cloud_sql_instances
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['-c', 'gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy']
availableSecrets:
  secretManager:
  - versionName: projects/531807919327/secrets/DB_HOST/versions/1
    env: 'DB_HOST'
  - versionName: projects/531807919327/secrets/DB_USER/versions/1
    env: 'DB_USER'
  - versionName: projects/531807919327/secrets/DB_PASSWORD/versions/1
    env: 'DB_PASSWORD'
  - versionName: projects/531807919327/secrets/DB_DATABASE/versions/1
    env: 'DB_DATABASE'
  - versionName: projects/531807919327/secrets/DB_DIALECT/versions/1
    env: 'DB_DIALECT'
  - versionName: projects/531807919327/secrets/DB_SOCKET/versions/1
    env: 'DB_SOCKET'
  - versionName: projects/531807919327/secrets/APP_ENV/versions/1
    env: 'APP_ENV'
  - versionName: projects/531807919327/secrets/JWT_SECRET_KEY/versions/1
    env: 'JWT_SECRET_KEY'
  - versionName: projects/531807919327/secrets/OPENAI_API_KEY/versions/1
    env: 'OPENAI_API_KEY'
  - versionName: projects/531807919327/secrets/cloud_sql_instances/versions/1
    env: 'cloud_sql_instances'
timeout: '1600s'
